name: idiomatic-pandas
channels:
- conda-forge
dependencies:
- pandas
- toolz
- requests_cache
- requests
- nbconvert
- matplotlib_venn
- importnb
- ibis-framework
- seaborn
- feather-format
- lxml
- IPython>=7.0
- networkx
- scikit-learn